spring:
  application:
    name: gatewayWithSleuth
  sleuth:
    enabled: true
    reactor:
      # instrumentation-type: decorate-on-each
      instrumentation-type: decorate-queues
      # instrumentation-type: manual
